//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuxyboxIdentity.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOrder
    {
        public int Id { get; set; }
        public string ShipmentAdress { get; set; }
        public string InvoiceAdress { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int SessionId { get; set; }
        public string NameSurname { get; set; }
        public string InvoiceName { get; set; }
    }
}
